src/main/webapp/good.js/closure-library/closure/bin/build/closurebuilder.py \
  --root=src/main/webapp/good.js/closure-library/ \
  --root=src/main/webapp/good.js/good/ \
  --root=src/main/webapp/good/ \
  --namespace="good.drive.init" \
  --output_mode=compiled \
  --compiler_jar=$HOME/.m2/repository/com/goodow/javascript/closure-compiler/v20130603-SNAPSHOT/closure-compiler-v20130603-SNAPSHOT.jar \
  --compiler_flags="--compilation_level=ADVANCED_OPTIMIZATIONS" \
  --compiler_flags="--externs=src/main/webapp/good.js/good/realtime/realtime.externs.js" \
  > src/main/webapp/compiled.js
