// This file was autogenerated by src/main/webapp/good.js/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../good/drive/demo.js', ['good.drive.demo'], []);
goog.addDependency('../../../../good/drive/init.js', ['good.drive.init'], ['good.auth', 'good.config', 'good.drive.nav.button', 'good.drive.nav.folders', 'good.drive.nav.menu', 'goog.dom']);
goog.addDependency('../../../../good/drive/nav/button/renderer.js', ['good.drive.nav.button.Renderer'], ['goog.a11y.aria.Role', 'goog.dom.NodeType', 'goog.dom.classes', 'goog.string', 'goog.ui.CustomButtonRenderer', 'goog.ui.INLINE_BLOCK_CLASSNAME']);
goog.addDependency('../../../../good/drive/nav/button/view.js', ['good.drive.nav.button'], ['good.drive.nav.button.Renderer', 'goog.dom', 'goog.ui.CustomButton']);
goog.addDependency('../../../../good/drive/nav/folders/model.js', ['good.drive.nav.folders.Model'], []);
goog.addDependency('../../../../good/drive/nav/folders/view.js', ['good.drive.nav.folders'], ['good.drive.nav.folders.Model', 'goog.ui.tree.TreeControl']);
goog.addDependency('../../../../good/drive/nav/menu/renderer.js', ['good.drive.nav.menu.ViewRenderer'], ['goog.ui.MenuRenderer']);
goog.addDependency('../../../../good/drive/nav/menu/view.js', ['good.drive.nav.menu'], ['good.drive.nav.menu.ViewRenderer', 'goog.dom', 'goog.positioning.Corner', 'goog.ui.ContainerRenderer', 'goog.ui.ControlRenderer', 'goog.ui.Menu', 'goog.ui.MenuItemRenderer', 'goog.ui.PopupMenu', 'goog.ui.SubMenu', 'goog.ui.registry']);
goog.addDependency('../../../good/auth/login.js', ['good.auth', 'good.auth.login'], ['good.config', 'good.net.CrossDomainRpc', 'goog.Uri', 'goog.Uri.QueryData', 'goog.dom', 'goog.events']);
goog.addDependency('../../../good/auth/signup.js', ['good.auth.signup'], ['good.config', 'good.net.CrossDomainRpc', 'goog.dom', 'goog.events']);
goog.addDependency('../../../good/config/config.js', ['good.config'], []);
goog.addDependency('../../../good/net/crossdomainrpc.js', ['good.net.CrossDomainRpc'], ['goog.json']);
