// This file was autogenerated by src/main/webapp/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../good/drive/demo.js', ['good.drive.demo'], ['good.net.CrossDomainRpc']);
goog.addDependency('../../../good/drive/nav/folders/view.js', ['good.drive.nav.folders.view'], ['goog.dom', 'goog.ui.tree.TreeControl']);
goog.addDependency('../../../good/net/crossdomainrpc.js', ['good.net.CrossDomainRpc'], []);
